apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend_intro_devops_casino
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend_intro_devops_casino
  template:
    metadata:
      labels:
        app: frontend_intro_devops_casino
    spec:
      # Regla para forzar el reparto de pods entre nodos (requisito del lab 3.3)
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: frontend_intro_devops_casino
      containers:
      - name: frontend_intro_devops_casino
        # Los marcadores <ACCOUNT_ID> y <REGION> serán reemplazados automáticamente por GitHub Actions
        image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/frontend_intro_devops_casino:latest
        ports:
        - containerPort: 8080

        resources:
          requests:
            cpu: "50m" # Obligatorio para que el HPA pueda calcular el % de uso
          limits:
            cpu: "250m"
      
      # Sondas de salud adaptadas para Nginx (Frontend)
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10